### ISSUE TITLE
Dockerize the app

### ISSUE THREAD

**Issue by debrahwyatt** [uvicaiclub/ai-club-website#74]
Setting up Docker would be a good way of maintaining build consistency across all platforms, so let's do it.

ACCEPTANCE CRITERIA:
- Research how to make a basic Docker build
- Set up the Docker to run on a Linux environment (possibly Ubuntu)

OPTIONAL:
- Try to get a development container set up for it configured for VS Code

**Comment by henryclw** [comment]
Do you need any help in docker? I could do this.
(But if we push the docker image to docker hub, this means all the source code will be published, everyone could know about it.)
